import json
import time
from collections.abc import Awaitable, Callable
from datetime import datetime
from enum import StrEnum
from typing import Any
from zoneinfo import ZoneInfo

import structlog

from app.chat.tools import RENAME_TOOL, execute_tool, tools_for_scopes
from app.integrations.anthropic import AnthropicClient

logger = structlog.get_logger(__name__)
MAX_TOKENS = 4096
MAX_TOOL_ITERATIONS = 5


class ChatStatus(StrEnum):
    """Deterministic, orchestration-driven — never generated by Claude.
    `verifying` (request handoff/auth) is deliberately not modeled here;
    it happens before this loop even starts and can stay frontend-only."""

    UNDERSTANDING = "understanding"
    FETCHING_DATA = "fetching_data"
    ANALYZING = "analyzing"
    RESPONDING = "responding"


StatusCallback = Callable[[ChatStatus], Awaitable[None]]
TITLE_SYSTEM_PROMPT = (
    "Summarize the user's message into a short conversation title (at most "
    "6 words, no surrounding quotes or trailing punctuation). Respond with "
    "only the title."
)


def build_system_prompt() -> str:
    now = datetime.now(ZoneInfo("Asia/Jakarta"))
    return (
        "You are FreshBrain, an internal AI assistant for Fresh Factory "
        "(cold chain, warehouse, and logistics operations).\n\n"
        f"Current datetime: {now:%Y-%m-%d %H:%M:%S} WIB (Asia/Jakarta).\n\n"
        "Use the available tools to answer operational questions accurately. "
        "If a question requires data you don't have a tool for, say so rather "
        "than guessing.\n\n"
        "If the user pastes a password, API key, token, or other credential "
        "into the conversation, don't repeat it back verbatim — warn them "
        "that it may have been exposed and suggest they rotate it."
    )


async def run_chat_loop(
    messages: list[dict[str, Any]],
    allowed_scopes: list[str],
    allow_rename: bool = False,
    client: AnthropicClient | None = None,
    on_status: StatusCallback | None = None,
) -> tuple[list[dict[str, Any]], str | None]:
    async def emit(status: ChatStatus) -> None:
        if on_status is not None:
            await on_status(status)

    model_client = client or AnthropicClient()
    working_messages = list(messages)
    new_messages: list[dict[str, Any]] = []
    renamed_title: str | None = None
    tools = tools_for_scopes(allowed_scopes)
    if allow_rename:
        tools.append(RENAME_TOOL)

    for iteration in range(MAX_TOOL_ITERATIONS):
        # First call: still figuring out what the user wants. Subsequent
        # calls only happen after tool results came back, i.e. Claude is
        # synthesizing over data it already fetched.
        await emit(ChatStatus.UNDERSTANDING if iteration == 0 else ChatStatus.ANALYZING)
        response = await model_client.create_message(
            system=build_system_prompt(),
            tools=tools,
            messages=working_messages,
            max_tokens=MAX_TOKENS,
            allowed_scopes=allowed_scopes,
        )
        assistant_message = {
            "role": "assistant",
            "content": [block.model_dump() for block in response.content],
        }
        working_messages.append(assistant_message)
        new_messages.append(assistant_message)

        if response.stop_reason != "tool_use":
            await emit(ChatStatus.RESPONDING)
            return new_messages, renamed_title

        await emit(ChatStatus.FETCHING_DATA)
        results = []
        for block in response.content:
            if block.type != "tool_use":
                continue
            if block.name == "rename_conversation":
                renamed_title = block.input.get("title")
                result = {"status": "renamed", "title": renamed_title}
            else:
                tool_start = time.perf_counter()
                result = await execute_tool(block.name, block.input, allowed_scopes)
                logger.info(
                    "tool_completed",
                    tool=block.name,
                    duration_ms=round((time.perf_counter() - tool_start) * 1000, 2),
                )
            results.append(
                {
                    "type": "tool_result",
                    "tool_use_id": block.id,
                    "content": json.dumps(result),
                }
            )

        tool_result_message = {"role": "user", "content": results}
        working_messages.append(tool_result_message)
        new_messages.append(tool_result_message)

    logger.warning("Reached tool iteration limit without a final response")
    await emit(ChatStatus.RESPONDING)
    return new_messages, renamed_title


async def generate_title(message: str) -> str:
    return await AnthropicClient().generate_title(message, TITLE_SYSTEM_PROMPT)
